name: Bug Report
description: Report a bug or unexpected behavior in the CDN Analytics Dashboard
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug and how to reproduce it.
      placeholder: |
        What went wrong...
        
        Steps to reproduce:
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Drag and drop screenshots showing the issue. This helps us understand the problem quickly.
      placeholder: Paste or drag screenshots here...
    validations:
      required: false

  - type: textarea
    id: errors
    attributes:
      label: Error messages (if any)
      description: Console errors (F12) or ClickHouse query errors.
      render: shell
