-- Tech Stack Migration: cloudflare_http_ingestion_v2
-- Changes helix.backend_type from 'cloudflare (implied)' to categorized tech stack values

DROP TABLE IF EXISTS helix_logs_production.cloudflare_http_ingestion_v2;

CREATE MATERIALIZED VIEW helix_logs_production.cloudflare_http_ingestion_v2 TO helix_logs_production.cdn_requests_v2
(
    `timestamp` DateTime64(9),
    `source` String,
    `cdn.cache_status` LowCardinality(String),
    `cdn.cache_ttl` UInt8,
    `cdn.datacenter` LowCardinality(String),
    `cdn.is_edge` Bool,
    `cdn.originating_ip` String,
    `cdn.region_code` LowCardinality(String),
    `cdn.time_elapsed_msec` UInt32,
    `cdn.url` String,
    `cdn.version` String,
    `client.city_name` String,
    `client.country_name` LowCardinality(String),
    `client.ip` String,
    `client.name` String,
    `client.asn` UInt32,
    `helix.backend_type` String,
    `helix.contentbus_prefix` String,
    `helix.request_type` String,
    `request.backend` String,
    `request.body_size` UInt8,
    `request.host` String,
    `request.method` LowCardinality(String),
    `request.protocol` LowCardinality(String),
    `request.url` String,
    `request.qs` String,
    `request.is_mixed_case` Bool,
    `request.restarts` UInt8,
    `request.headers.accept` String,
    `request.headers.accept_content` String,
    `request.headers.accept_encoding` String,
    `request.headers.accept_language` String,
    `request.headers.cache_control` String,
    `request.headers.cdn_loop` String,
    `request.headers.cf_connecting_ip` String,
    `request.headers.if_modified_since` String,
    `request.headers.if_none_match` String,
    `request.headers.range` String,
    `request.headers.referer` String,
    `request.headers.true_client_ip` String,
    `request.headers.user_agent` String,
    `request.headers.via` String,
    `request.headers.x_byo_cdn_type` String,
    `request.headers.x_forwarded_for` String,
    `request.headers.x_forwarded_host` String,
    `request.headers.x_hipaa` String,
    `request.headers.x_push_invalidation` String,
    `response.status` UInt16,
    `response.body_size` UInt64,
    `response.headers.cache_control` String,
    `response.headers.cache_tag` String,
    `response.headers.cdn_cache_control` String,
    `response.headers.cf_resized` String,
    `response.headers.content_encoding` String,
    `response.headers.content_length` UInt64,
    `response.headers.content_range` String,
    `response.headers.content_type` LowCardinality(String),
    `response.headers.edge_cache_tag` String,
    `response.headers.edge_control` String,
    `response.headers.etag` String,
    `response.headers.expires` String,
    `response.headers.last_modified` DateTime64(3),
    `response.headers.location` String,
    `response.headers.surrogate_control` String,
    `response.headers.surrogate_key` String,
    `response.headers.vary` String,
    `response.headers.x_error` String,
    `response.headers.x_robots_tag` String,
    `response.headers.x_surrogate_key` String
)
AS SELECT
    fromUnixTimestamp64Nano(EdgeStartTimestamp) AS timestamp,
    'cloudflare' AS source,
    CacheCacheStatus AS `cdn.cache_status`,
    0 AS `cdn.cache_ttl`,
    EdgeColoCode AS `cdn.datacenter`,
    true AS `cdn.is_edge`,
    ClientIP AS `cdn.originating_ip`,
    ClientRegionCode AS `cdn.region_code`,
    EdgeTimeToFirstByteMs AS `cdn.time_elapsed_msec`,
    concat('https://', ClientRequestHost, ClientRequestURI) AS `cdn.url`,
    '' AS `cdn.version`,
    '' AS `client.city_name`,
    ClientCountry AS `client.country_name`,
    ClientIP AS `client.ip`,
    '' AS `client.name`,
    ClientASN AS `client.asn`,
    -- NEW: Tech stack categorization based on host patterns
    multiIf(
        ClientRequestHost LIKE '%.r2.cloudflarestorage.com', 'Cloudflare / R2',
        ClientRequestHost LIKE '%da.live', 'Cloudflare / DA',
        ClientRequestHost LIKE '%.aem.network', 'Cloudflare / Helix',
        'Cloudflare / Workers'
    ) AS `helix.backend_type`,
    '' AS `helix.contentbus_prefix`,
    '' AS `helix.request_type`,
    '' AS `request.backend`,
    0 AS `request.body_size`,
    ClientRequestHost AS `request.host`,
    ClientRequestMethod AS `request.method`,
    ClientRequestProtocol AS `request.protocol`,
    ClientRequestURI AS `request.url`,
    '' AS `request.qs`,
    false AS `request.is_mixed_case`,
    0 AS `request.restarts`,
    JSON_VALUE(RequestHeaders, '$["accept"]') AS `request.headers.accept`,
    JSON_VALUE(RequestHeaders, '$["accept-content"]') AS `request.headers.accept_content`,
    JSON_VALUE(RequestHeaders, '$["accept-encoding"]') AS `request.headers.accept_encoding`,
    JSON_VALUE(RequestHeaders, '$["accept-language"]') AS `request.headers.accept_language`,
    JSON_VALUE(RequestHeaders, '$["cache-control"]') AS `request.headers.cache_control`,
    JSON_VALUE(RequestHeaders, '$["cdn-loop"]') AS `request.headers.cdn_loop`,
    JSON_VALUE(RequestHeaders, '$["cf-connecting-ip"]') AS `request.headers.cf_connecting_ip`,
    JSON_VALUE(RequestHeaders, '$["if-modified-since"]') AS `request.headers.if_modified_since`,
    JSON_VALUE(RequestHeaders, '$["if-none-match"]') AS `request.headers.if_none_match`,
    JSON_VALUE(RequestHeaders, '$["range"]') AS `request.headers.range`,
    ClientRequestReferer AS `request.headers.referer`,
    JSON_VALUE(RequestHeaders, '$["true-client-ip"]') AS `request.headers.true_client_ip`,
    ClientRequestUserAgent AS `request.headers.user_agent`,
    JSON_VALUE(RequestHeaders, '$.via') AS `request.headers.via`,
    JSON_VALUE(RequestHeaders, '$["x-byo-cdn-type"]') AS `request.headers.x_byo_cdn_type`,
    JSON_VALUE(RequestHeaders, '$["x-forwarded-for"]') AS `request.headers.x_forwarded_for`,
    JSON_VALUE(RequestHeaders, '$["x-forwarded-host"]') AS `request.headers.x_forwarded_host`,
    JSON_VALUE(RequestHeaders, '$["x-hipaa"]') AS `request.headers.x_hipaa`,
    JSON_VALUE(RequestHeaders, '$["x-push-invalidation"]') AS `request.headers.x_push_invalidation`,
    EdgeResponseStatus AS `response.status`,
    EdgeResponseBytes AS `response.body_size`,
    JSON_VALUE(ResponseHeaders, '$["cache-control"]') AS `response.headers.cache_control`,
    JSON_VALUE(ResponseHeaders, '$["cache-tag"]') AS `response.headers.cache_tag`,
    JSON_VALUE(ResponseHeaders, '$["cdn-cache-control"]') AS `response.headers.cdn_cache_control`,
    JSON_VALUE(ResponseHeaders, '$["cf-resized"]') AS `response.headers.cf_resized`,
    JSON_VALUE(ResponseHeaders, '$["content-encoding"]') AS `response.headers.content_encoding`,
    toUInt64OrZero(JSON_VALUE(ResponseHeaders, '$["content-length"]')) AS `response.headers.content_length`,
    JSON_VALUE(ResponseHeaders, '$["content-range"]') AS `response.headers.content_range`,
    EdgeResponseContentType AS `response.headers.content_type`,
    JSON_VALUE(ResponseHeaders, '$["edge-cache-tag"]') AS `response.headers.edge_cache_tag`,
    JSON_VALUE(ResponseHeaders, '$["edge-control"]') AS `response.headers.edge_control`,
    JSON_VALUE(ResponseHeaders, '$["etag"]') AS `response.headers.etag`,
    JSON_VALUE(ResponseHeaders, '$["expires"]') AS `response.headers.expires`,
    parseDateTime64BestEffortOrZero(JSON_VALUE(ResponseHeaders, '$["last-modified"]'), 3) AS `response.headers.last_modified`,
    JSON_VALUE(ResponseHeaders, '$.location') AS `response.headers.location`,
    JSON_VALUE(ResponseHeaders, '$["surrogate-control"]') AS `response.headers.surrogate_control`,
    JSON_VALUE(ResponseHeaders, '$["surrogate-key"]') AS `response.headers.surrogate_key`,
    JSON_VALUE(ResponseHeaders, '$.vary') AS `response.headers.vary`,
    JSON_VALUE(ResponseHeaders, '$["x-error"]') AS `response.headers.x_error`,
    JSON_VALUE(ResponseHeaders, '$["x-robots-tag"]') AS `response.headers.x_robots_tag`,
    JSON_VALUE(ResponseHeaders, '$["x-surrogate-key"]') AS `response.headers.x_surrogate_key`
FROM helix_logs_production.cloudflare_http_requests
WHERE (ClientRequestHost NOT IN ('s2p5b8wmt5.eastus2.azure.clickhouse.cloud:8443', 'ogadftwx3q.us-east1.gcp.clickhouse.cloud:8443', 'ingress.eu1.coralogix.com')) AND (ClientRequestSource != 'edgeWorkerCacheAPI');
