-- Tech Stack Migration: fastly_ingestion_v2 (main helix5 service)
-- Changes helix.backend_type from raw value to categorized tech stack values

DROP TABLE IF EXISTS helix_logs_production.fastly_ingestion_v2;

CREATE MATERIALIZED VIEW helix_logs_production.fastly_ingestion_v2 TO helix_logs_production.cdn_requests_v2
(
    `timestamp` DateTime64(3),
    `source` String,
    `cdn.cache_status` String,
    `cdn.cache_ttl` Float64,
    `cdn.datacenter` String,
    `cdn.is_edge` Bool,
    `cdn.originating_ip` String,
    `cdn.region_code` String,
    `cdn.time_elapsed_msec` Float64,
    `cdn.url` String,
    `cdn.version` String,
    `client.city_name` String,
    `client.country_name` String,
    `client.ip` String,
    `client.name` String,
    `client.asn` UInt32,
    `helix.backend_type` String,
    `helix.contentbus_prefix` String,
    `helix.request_type` String,
    `request.backend` String,
    `request.body_size` UInt64,
    `request.host` String,
    `request.method` String,
    `request.protocol` String,
    `request.url` String,
    `request.qs` String,
    `request.is_mixed_case` Bool,
    `request.restarts` UInt8,
    `request.headers.accept_encoding` String,
    `request.headers.accept_language` String,
    `request.headers.cache_control` String,
    `request.headers.cdn_loop` String,
    `request.headers.referer` String,
    `request.headers.user_agent` String,
    `request.headers.via` String,
    `request.headers.x_forwarded_for` String,
    `request.headers.x_forwarded_host` String,
    `request.headers.x_byo_cdn_type` String,
    `request.headers.x_push_invalidation` String,
    `response.status` UInt16,
    `response.body_size` UInt64,
    `response.headers.cache_control` String,
    `response.headers.content_type` String,
    `response.headers.content_encoding` String,
    `response.headers.content_length` UInt64,
    `response.headers.vary` String,
    `response.headers.last_modified` DateTime64(9),
    `response.headers.location` String,
    `response.headers.x_error` String,
    `response.headers.x_surrogate_key` String,
    `response.headers.edge_cache_tag` String,
    `response.headers.edge_control` String
)
AS SELECT
    toDateTime64(timestamp / 1000, 3) AS timestamp,
    'fastly' AS source,
    json.cdn.cache_status AS `cdn.cache_status`,
    json.cdn.cache_ttl AS `cdn.cache_ttl`,
    json.cdn.datacenter AS `cdn.datacenter`,
    json.cdn.is_edge AS `cdn.is_edge`,
    json.cdn.originating_ip AS `cdn.originating_ip`,
    json.cdn.region_code AS `cdn.region_code`,
    json.cdn.time_elapsed_msec AS `cdn.time_elapsed_msec`,
    json.cdn.url AS `cdn.url`,
    json.cdn.version AS `cdn.version`,
    json.client.city_name AS `client.city_name`,
    json.client.country_name AS `client.country_name`,
    json.client.ip AS `client.ip`,
    json.client.name AS `client.name`,
    toUInt32(json.client.number) AS `client.asn`,
    -- NEW: Tech stack categorization
    multiIf(
        json.helix.request_type = 'media', 'Fastly / Image Optimizer',
        json.request.host LIKE 'admin.hlx.%' OR json.request.host LIKE 'admin.aem.%', 'Fastly / Admin',
        json.request.host LIKE 'api.aem.%' OR json.request.host LIKE 'api.hlx.%', 'Fastly / API',
        json.request.host LIKE 'www.aem.%' OR json.request.host LIKE 'www.hlx.%', 'Fastly / WWW',
        json.helix.backend_type = 'aws', 'Fastly / AWS',
        json.helix.backend_type = 'cloudflare', 'Fastly / Cloudflare',
        'Fastly / Other'
    ) AS `helix.backend_type`,
    json.helix.contentbus_prefix AS `helix.contentbus_prefix`,
    json.helix.request_type AS `helix.request_type`,
    json.request.backend AS `request.backend`,
    toUInt64(json.request.body_size) AS `request.body_size`,
    json.request.host AS `request.host`,
    json.request.method AS `request.method`,
    json.request.protocol AS `request.protocol`,
    json.request.url AS `request.url`,
    json.request.qs AS `request.qs`,
    json.request.is_mixed_case AS `request.is_mixed_case`,
    toUInt8(json.request.restarts) AS `request.restarts`,
    json.request.headers.accept_encoding AS `request.headers.accept_encoding`,
    json.request.headers.accept_language AS `request.headers.accept_language`,
    json.request.headers.cache_control AS `request.headers.cache_control`,
    json.request.headers.cdn_loop AS `request.headers.cdn_loop`,
    json.request.headers.referer AS `request.headers.referer`,
    json.request.headers.user_agent AS `request.headers.user_agent`,
    json.request.headers.via AS `request.headers.via`,
    json.request.headers.x_forwarded_for AS `request.headers.x_forwarded_for`,
    json.request.headers.x_forwarded_host AS `request.headers.x_forwarded_host`,
    json.request.headers.x_byo_cdn_type AS `request.headers.x_byo_cdn_type`,
    json.request.headers.x_push_invalidation AS `request.headers.x_push_invalidation`,
    toUInt16OrZero(json.response.status) AS `response.status`,
    toUInt64(json.response.body_size) AS `response.body_size`,
    json.response.headers.cache_control AS `response.headers.cache_control`,
    json.response.headers.content_type AS `response.headers.content_type`,
    json.response.headers.content_encoding AS `response.headers.content_encoding`,
    toUInt64OrZero(json.response.headers.content_length) AS `response.headers.content_length`,
    json.response.headers.vary AS `response.headers.vary`,
    json.response.headers.last_modified AS `response.headers.last_modified`,
    json.response.headers.location AS `response.headers.location`,
    json.response.headers.x_error AS `response.headers.x_error`,
    json.response.headers.x_surrogate_key AS `response.headers.x_surrogate_key`,
    json.response.headers.edge_cache_tag AS `response.headers.edge_cache_tag`,
    json.response.headers.edge_control AS `response.headers.edge_control`
FROM helix_logs_production.fastly_logs_incoming2;
