-- Tech Stack Migration: fastly_ingestion_form_v2
-- Changes helix.backend_type from '' to 'Fastly / Forms'

DROP TABLE IF EXISTS helix_logs_production.fastly_ingestion_form_v2;

CREATE MATERIALIZED VIEW helix_logs_production.fastly_ingestion_form_v2 TO helix_logs_production.cdn_requests_v2
(
    `timestamp` DateTime64(3),
    `source` String,
    `cdn.cache_status` String,
    `cdn.cache_ttl` UInt8,
    `cdn.datacenter` String,
    `cdn.is_edge` Bool,
    `cdn.originating_ip` String,
    `cdn.region_code` String,
    `cdn.time_elapsed_msec` Float64,
    `cdn.url` String,
    `cdn.version` String,
    `client.city_name` String,
    `client.country_name` String,
    `client.ip` String,
    `client.name` String,
    `client.asn` UInt32,
    `helix.backend_type` String,
    `helix.contentbus_prefix` String,
    `helix.request_type` String,
    `request.backend` String,
    `request.body_size` UInt64,
    `request.host` String,
    `request.method` String,
    `request.protocol` String,
    `request.url` String,
    `request.qs` String,
    `request.is_mixed_case` Bool,
    `request.restarts` UInt8,
    `request.headers.accept_encoding` String,
    `request.headers.accept_language` String,
    `request.headers.cache_control` String,
    `request.headers.cdn_loop` String,
    `request.headers.referer` String,
    `request.headers.user_agent` String,
    `request.headers.via` String,
    `request.headers.x_forwarded_for` String,
    `request.headers.x_forwarded_host` String,
    `request.headers.x_byo_cdn_type` String,
    `request.headers.x_push_invalidation` String,
    `response.status` UInt16,
    `response.body_size` UInt64,
    `response.headers.cache_control` String,
    `response.headers.content_type` String,
    `response.headers.content_encoding` String,
    `response.headers.content_length` UInt64,
    `response.headers.vary` String,
    `response.headers.last_modified` DateTime64(3),
    `response.headers.location` String,
    `response.headers.x_error` String,
    `response.headers.x_surrogate_key` String,
    `response.headers.edge_cache_tag` String,
    `response.headers.edge_control` String
)
AS SELECT
    toDateTime64(timestamp / 1000, 3) AS timestamp,
    'fastly' AS source,
    '' AS `cdn.cache_status`,
    0 AS `cdn.cache_ttl`,
    text.cdn.datacenter AS `cdn.datacenter`,
    false AS `cdn.is_edge`,
    text.cdn.originating_ip AS `cdn.originating_ip`,
    text.cdn.region_code AS `cdn.region_code`,
    toFloat64(text.cdn.time.elapsed) / 1000. AS `cdn.time_elapsed_msec`,
    text.cdn.url AS `cdn.url`,
    text.cdn.version AS `cdn.version`,
    text.cdn.client.city_name AS `client.city_name`,
    text.cdn.client.country_name AS `client.country_name`,
    text.cdn.client.ip AS `client.ip`,
    text.cdn.client.name AS `client.name`,
    toUInt32(text.cdn.client.number) AS `client.asn`,
    -- NEW: Fixed tech stack value
    'Fastly / Forms' AS `helix.backend_type`,
    '' AS `helix.contentbus_prefix`,
    'form' AS `helix.request_type`,
    text.cdn.request.backend AS `request.backend`,
    toUInt64(text.cdn.request.body_size) AS `request.body_size`,
    text.cdn.request.host AS `request.host`,
    text.cdn.request.method AS `request.method`,
    text.cdn.request.protocol AS `request.protocol`,
    text.cdn.request.url AS `request.url`,
    '' AS `request.qs`,
    false AS `request.is_mixed_case`,
    0 AS `request.restarts`,
    '' AS `request.headers.accept_encoding`,
    '' AS `request.headers.accept_language`,
    '' AS `request.headers.cache_control`,
    '' AS `request.headers.cdn_loop`,
    text.cdn.request.headers.referer AS `request.headers.referer`,
    text.cdn.request.headers.user_agent AS `request.headers.user_agent`,
    '' AS `request.headers.via`,
    text.cdn.request.headers.x_forwarded_for AS `request.headers.x_forwarded_for`,
    text.cdn.request.headers.x_forwarded_host AS `request.headers.x_forwarded_host`,
    '' AS `request.headers.x_byo_cdn_type`,
    '' AS `request.headers.x_push_invalidation`,
    toUInt16OrZero(text.cdn.response.status) AS `response.status`,
    toUInt64(text.cdn.response.body_size) AS `response.body_size`,
    '' AS `response.headers.cache_control`,
    '' AS `response.headers.content_type`,
    '' AS `response.headers.content_encoding`,
    toUInt64(text.cdn.response.body_size) AS `response.headers.content_length`,
    '' AS `response.headers.vary`,
    toDateTime64(0, 3) AS `response.headers.last_modified`,
    '' AS `response.headers.location`,
    text.cdn.response.headers.x_error AS `response.headers.x_error`,
    '' AS `response.headers.x_surrogate_key`,
    '' AS `response.headers.edge_cache_tag`,
    '' AS `response.headers.edge_control`
FROM helix_logs_production.fastly_logs_incoming_UDBDj4zfyNdZEpZApUqhL3;
