-- Tech Stack Migration: cloudflare_http_ingestion_v2
-- Changes helix.backend_type from 'cloudflare (implied)' to categorized tech stack values

DROP TABLE IF EXISTS helix_logs_production.cloudflare_http_ingestion_v2;

CREATE MATERIALIZED VIEW helix_logs_production.cloudflare_http_ingestion_v2 TO helix_logs_production.cdn_requests_v2
(
    `timestamp` DateTime64(9),
    `source` String,
    `cdn.cache_status` LowCardinality(String),
    `cdn.cache_ttl` UInt8,
    `cdn.datacenter` LowCardinality(String),
    `cdn.is_edge` Bool,
    `cdn.originating_ip` String,
    `cdn.region_code` LowCardinality(String),
    `cdn.time_elapsed_msec` UInt32,
    `cdn.url` String,
    `cdn.version` String,
    `client.city_name` String,
    `client.country_name` LowCardinality(String),
    `client.ip` String,
    `client.name` String,
    `client.asn` UInt32,
    `helix.backend_type` String,
    `helix.contentbus_prefix` String,
    `helix.request_type` String,
    `request.backend` String,
    `request.body_size` UInt8,
    `request.host` String,
    `request.method` LowCardinality(String),
    `request.protocol` LowCardinality(String),
    `request.url` String,
    `request.qs` String,
    `request.is_mixed_case` Bool,
    `request.restarts` UInt8,
    `request.headers.accept` String,
    `request.headers.accept_content` String,
    `request.headers.accept_encoding` String,
    `request.headers.accept_language` String,
    `request.headers.cache_control` String,
    `request.headers.cdn_loop` String,
    `request.headers.cf_connecting_ip` String,
    `request.headers.if_modified_since` String,
    `request.headers.if_none_match` String,
    `request.headers.range` String,
    `request.headers.referer` String,
    `request.headers.true_client_ip` String,
    `request.headers.user_agent` String,
    `request.headers.via` String,
    `request.headers.x_byo_cdn_type` String,
    `request.headers.x_forwarded_for` String,
    `request.headers.x_forwarded_host` String,
    `request.headers.x_hipaa` String,
    `request.headers.x_push_invalidation` String,
    `response.status` UInt16,
    `response.body_size` UInt64,
    `response.headers.cache_control` String,
    `response.headers.cache_tag` String,
    `response.headers.cdn_cache_control` String,
    `response.headers.cf_resized` String,
    `response.headers.content_encoding` String,
    `response.headers.content_length` UInt64,
    `response.headers.content_range` String,
    `response.headers.content_type` LowCardinality(String),
    `response.headers.edge_cache_tag` String,
    `response.headers.edge_control` String,
    `response.headers.etag` String,
    `response.headers.expires` String,
    `response.headers.last_modified` DateTime64(3),
    `response.headers.location` String,
    `response.headers.surrogate_control` String,
    `response.headers.surrogate_key` String,
    `response.headers.vary` String,
    `response.headers.x_error` String,
    `response.headers.x_robots_tag` String,
    `response.headers.x_surrogate_key` String
)
AS SELECT
    fromUnixTimestamp64Nano(EdgeStartTimestamp) AS timestamp,
    'cloudflare' AS source,
    CacheCacheStatus AS `cdn.cache_status`,
    0 AS `cdn.cache_ttl`,
    EdgeColoCode AS `cdn.datacenter`,
    true AS `cdn.is_edge`,
    ClientIP AS `cdn.originating_ip`,
    ClientRegionCode AS `cdn.region_code`,
    EdgeTimeToFirstByteMs AS `cdn.time_elapsed_msec`,
    concat('https://', ClientRequestHost, ClientRequestURI) AS `cdn.url`,
    '' AS `cdn.version`,
    '' AS `client.city_name`,
    ClientCountry AS `client.country_name`,
    ClientIP AS `client.ip`,
    '' AS `client.name`,
    ClientASN AS `client.asn`,
    -- NEW: Tech stack categorization based on host patterns
    multiIf(
        ClientRequestHost LIKE '%.r2.cloudflarestorage.com', 'Cloudflare / R2',
        ClientRequestHost LIKE '%da.live', 'Cloudflare / DA',
        ClientRequestHost LIKE '%.aem.network', 'Cloudflare / Helix',
        'Cloudflare / Workers'
    ) AS `helix.backend_type`,
    '' AS `helix.contentbus_prefix`,
    '' AS `helix.request_type`,
    '' AS `request.backend`,
    0 AS `request.body_size`,
    ClientRequestHost AS `request.host`,
    ClientRequestMethod AS `request.method`,
    ClientRequestProtocol AS `request.protocol`,
    ClientRequestURI AS `request.url`,
    '' AS `request.qs`,
    false AS `request.is_mixed_case`,
    0 AS `request.restarts`,
    JSON_VALUE(RequestHeaders, '$["accept"]') AS `request.headers.accept`,
    JSON_VALUE(RequestHeaders, '$["accept-content"]') AS `request.headers.accept_content`,
    JSON_VALUE(RequestHeaders, '$["accept-encoding"]') AS `request.headers.accept_encoding`,
    JSON_VALUE(RequestHeaders, '$["accept-language"]') AS `request.headers.accept_language`,
    JSON_VALUE(RequestHeaders, '$["cache-control"]') AS `request.headers.cache_control`,
    JSON_VALUE(RequestHeaders, '$["cdn-loop"]') AS `request.headers.cdn_loop`,
    JSON_VALUE(RequestHeaders, '$["cf-connecting-ip"]') AS `request.headers.cf_connecting_ip`,
    JSON_VALUE(RequestHeaders, '$["if-modified-since"]') AS `request.headers.if_modified_since`,
    JSON_VALUE(RequestHeaders, '$["if-none-match"]') AS `request.headers.if_none_match`,
    JSON_VALUE(RequestHeaders, '$["range"]') AS `request.headers.range`,
    ClientRequestReferer AS `request.headers.referer`,
    JSON_VALUE(RequestHeaders, '$["true-client-ip"]') AS `request.headers.true_client_ip`,
    ClientRequestUserAgent AS `request.headers.user_agent`,
    JSON_VALUE(RequestHeaders, '$.via') AS `request.headers.via`,
    JSON_VALUE(RequestHeaders, '$["x-byo-cdn-type"]') AS `request.headers.x_byo_cdn_type`,
    JSON_VALUE(RequestHeaders, '$["x-forwarded-for"]') AS `request.headers.x_forwarded_for`,
    JSON_VALUE(RequestHeaders, '$["x-forwarded-host"]') AS `request.headers.x_forwarded_host`,
    JSON_VALUE(RequestHeaders, '$["x-hipaa"]') AS `request.headers.x_hipaa`,
    JSON_VALUE(RequestHeaders, '$["x-push-invalidation"]') AS `request.headers.x_push_invalidation`,
    EdgeResponseStatus AS `response.status`,
    EdgeResponseBytes AS `response.body_size`,
    JSON_VALUE(ResponseHeaders, '$["cache-control"]') AS `response.headers.cache_control`,
    JSON_VALUE(ResponseHeaders, '$["cache-tag"]') AS `response.headers.cache_tag`,
    JSON_VALUE(ResponseHeaders, '$["cdn-cache-control"]') AS `response.headers.cdn_cache_control`,
    JSON_VALUE(ResponseHeaders, '$["cf-resized"]') AS `response.headers.cf_resized`,
    JSON_VALUE(ResponseHeaders, '$["content-encoding"]') AS `response.headers.content_encoding`,
    toUInt64OrZero(JSON_VALUE(ResponseHeaders, '$["content-length"]')) AS `response.headers.content_length`,
    JSON_VALUE(ResponseHeaders, '$["content-range"]') AS `response.headers.content_range`,
    EdgeResponseContentType AS `response.headers.content_type`,
    JSON_VALUE(ResponseHeaders, '$["edge-cache-tag"]') AS `response.headers.edge_cache_tag`,
    JSON_VALUE(ResponseHeaders, '$["edge-control"]') AS `response.headers.edge_control`,
    JSON_VALUE(ResponseHeaders, '$["etag"]') AS `response.headers.etag`,
    JSON_VALUE(ResponseHeaders, '$["expires"]') AS `response.headers.expires`,
    parseDateTime64BestEffortOrZero(JSON_VALUE(ResponseHeaders, '$["last-modified"]'), 3) AS `response.headers.last_modified`,
    JSON_VALUE(ResponseHeaders, '$.location') AS `response.headers.location`,
    JSON_VALUE(ResponseHeaders, '$["surrogate-control"]') AS `response.headers.surrogate_control`,
    JSON_VALUE(ResponseHeaders, '$["surrogate-key"]') AS `response.headers.surrogate_key`,
    JSON_VALUE(ResponseHeaders, '$.vary') AS `response.headers.vary`,
    JSON_VALUE(ResponseHeaders, '$["x-error"]') AS `response.headers.x_error`,
    JSON_VALUE(ResponseHeaders, '$["x-robots-tag"]') AS `response.headers.x_robots_tag`,
    JSON_VALUE(ResponseHeaders, '$["x-surrogate-key"]') AS `response.headers.x_surrogate_key`
FROM helix_logs_production.cloudflare_http_requests
WHERE (ClientRequestHost NOT IN ('s2p5b8wmt5.eastus2.azure.clickhouse.cloud:8443', 'ogadftwx3q.us-east1.gcp.clickhouse.cloud:8443', 'ingress.eu1.coralogix.com')) AND (ClientRequestSource != 'edgeWorkerCacheAPI');
-- Tech Stack Migration: fastly_ingestion_v2 (main helix5 service)
-- Changes helix.backend_type from raw value to categorized tech stack values

DROP TABLE IF EXISTS helix_logs_production.fastly_ingestion_v2;

CREATE MATERIALIZED VIEW helix_logs_production.fastly_ingestion_v2 TO helix_logs_production.cdn_requests_v2
(
    `timestamp` DateTime64(3),
    `source` String,
    `cdn.cache_status` String,
    `cdn.cache_ttl` Float64,
    `cdn.datacenter` String,
    `cdn.is_edge` Bool,
    `cdn.originating_ip` String,
    `cdn.region_code` String,
    `cdn.time_elapsed_msec` Float64,
    `cdn.url` String,
    `cdn.version` String,
    `client.city_name` String,
    `client.country_name` String,
    `client.ip` String,
    `client.name` String,
    `client.asn` UInt32,
    `helix.backend_type` String,
    `helix.contentbus_prefix` String,
    `helix.request_type` String,
    `request.backend` String,
    `request.body_size` UInt64,
    `request.host` String,
    `request.method` String,
    `request.protocol` String,
    `request.url` String,
    `request.qs` String,
    `request.is_mixed_case` Bool,
    `request.restarts` UInt8,
    `request.headers.accept_encoding` String,
    `request.headers.accept_language` String,
    `request.headers.cache_control` String,
    `request.headers.cdn_loop` String,
    `request.headers.referer` String,
    `request.headers.user_agent` String,
    `request.headers.via` String,
    `request.headers.x_forwarded_for` String,
    `request.headers.x_forwarded_host` String,
    `request.headers.x_byo_cdn_type` String,
    `request.headers.x_push_invalidation` String,
    `response.status` UInt16,
    `response.body_size` UInt64,
    `response.headers.cache_control` String,
    `response.headers.content_type` String,
    `response.headers.content_encoding` String,
    `response.headers.content_length` UInt64,
    `response.headers.vary` String,
    `response.headers.last_modified` DateTime64(9),
    `response.headers.location` String,
    `response.headers.x_error` String,
    `response.headers.x_surrogate_key` String,
    `response.headers.edge_cache_tag` String,
    `response.headers.edge_control` String
)
AS SELECT
    toDateTime64(timestamp / 1000, 3) AS timestamp,
    'fastly' AS source,
    json.cdn.cache_status AS `cdn.cache_status`,
    json.cdn.cache_ttl AS `cdn.cache_ttl`,
    json.cdn.datacenter AS `cdn.datacenter`,
    json.cdn.is_edge AS `cdn.is_edge`,
    json.cdn.originating_ip AS `cdn.originating_ip`,
    json.cdn.region_code AS `cdn.region_code`,
    json.cdn.time_elapsed_msec AS `cdn.time_elapsed_msec`,
    json.cdn.url AS `cdn.url`,
    json.cdn.version AS `cdn.version`,
    json.client.city_name AS `client.city_name`,
    json.client.country_name AS `client.country_name`,
    json.client.ip AS `client.ip`,
    json.client.name AS `client.name`,
    toUInt32(json.client.number) AS `client.asn`,
    -- NEW: Tech stack categorization
    multiIf(
        json.helix.request_type = 'media', 'Fastly / Image Optimizer',
        json.request.host LIKE 'admin.hlx.%' OR json.request.host LIKE 'admin.aem.%', 'Fastly / Admin',
        json.request.host LIKE 'api.aem.%' OR json.request.host LIKE 'api.hlx.%', 'Fastly / API',
        json.request.host LIKE 'www.aem.%' OR json.request.host LIKE 'www.hlx.%', 'Fastly / WWW',
        json.helix.backend_type = 'aws', 'Fastly / AWS',
        json.helix.backend_type = 'cloudflare', 'Fastly / Cloudflare',
        'Fastly / Other'
    ) AS `helix.backend_type`,
    json.helix.contentbus_prefix AS `helix.contentbus_prefix`,
    json.helix.request_type AS `helix.request_type`,
    json.request.backend AS `request.backend`,
    toUInt64(json.request.body_size) AS `request.body_size`,
    json.request.host AS `request.host`,
    json.request.method AS `request.method`,
    json.request.protocol AS `request.protocol`,
    json.request.url AS `request.url`,
    json.request.qs AS `request.qs`,
    json.request.is_mixed_case AS `request.is_mixed_case`,
    toUInt8(json.request.restarts) AS `request.restarts`,
    json.request.headers.accept_encoding AS `request.headers.accept_encoding`,
    json.request.headers.accept_language AS `request.headers.accept_language`,
    json.request.headers.cache_control AS `request.headers.cache_control`,
    json.request.headers.cdn_loop AS `request.headers.cdn_loop`,
    json.request.headers.referer AS `request.headers.referer`,
    json.request.headers.user_agent AS `request.headers.user_agent`,
    json.request.headers.via AS `request.headers.via`,
    json.request.headers.x_forwarded_for AS `request.headers.x_forwarded_for`,
    json.request.headers.x_forwarded_host AS `request.headers.x_forwarded_host`,
    json.request.headers.x_byo_cdn_type AS `request.headers.x_byo_cdn_type`,
    json.request.headers.x_push_invalidation AS `request.headers.x_push_invalidation`,
    toUInt16OrZero(json.response.status) AS `response.status`,
    toUInt64(json.response.body_size) AS `response.body_size`,
    json.response.headers.cache_control AS `response.headers.cache_control`,
    json.response.headers.content_type AS `response.headers.content_type`,
    json.response.headers.content_encoding AS `response.headers.content_encoding`,
    toUInt64OrZero(json.response.headers.content_length) AS `response.headers.content_length`,
    json.response.headers.vary AS `response.headers.vary`,
    json.response.headers.last_modified AS `response.headers.last_modified`,
    json.response.headers.location AS `response.headers.location`,
    json.response.headers.x_error AS `response.headers.x_error`,
    json.response.headers.x_surrogate_key AS `response.headers.x_surrogate_key`,
    json.response.headers.edge_cache_tag AS `response.headers.edge_cache_tag`,
    json.response.headers.edge_control AS `response.headers.edge_control`
FROM helix_logs_production.fastly_logs_incoming2;
-- Tech Stack Migration: fastly_ingestion_media_v2
-- Changes helix.backend_type to 'Fastly / Image Optimizer'

DROP TABLE IF EXISTS helix_logs_production.fastly_ingestion_media_v2;

CREATE MATERIALIZED VIEW helix_logs_production.fastly_ingestion_media_v2 TO helix_logs_production.cdn_requests_v2
(
    `timestamp` DateTime64(3),
    `source` String,
    `cdn.cache_status` String,
    `cdn.cache_ttl` Float64,
    `cdn.datacenter` String,
    `cdn.is_edge` Bool,
    `cdn.originating_ip` String,
    `cdn.region_code` String,
    `cdn.time_elapsed_msec` Float64,
    `cdn.url` String,
    `cdn.version` String,
    `client.city_name` String,
    `client.country_name` String,
    `client.ip` String,
    `client.name` String,
    `client.asn` UInt32,
    `helix.backend_type` String,
    `helix.contentbus_prefix` String,
    `helix.request_type` String,
    `request.backend` String,
    `request.body_size` UInt8,
    `request.host` String,
    `request.method` String,
    `request.protocol` String,
    `request.url` String,
    `request.qs` String,
    `request.is_mixed_case` Bool,
    `request.restarts` UInt8,
    `request.headers.accept_encoding` String,
    `request.headers.accept_language` String,
    `request.headers.cache_control` String,
    `request.headers.cdn_loop` String,
    `request.headers.referer` String,
    `request.headers.user_agent` String,
    `request.headers.via` String,
    `request.headers.x_forwarded_for` String,
    `request.headers.x_forwarded_host` String,
    `request.headers.x_byo_cdn_type` String,
    `request.headers.x_push_invalidation` String,
    `response.status` UInt16,
    `response.body_size` UInt64,
    `response.headers.cache_control` String,
    `response.headers.content_type` String,
    `response.headers.content_encoding` String,
    `response.headers.content_length` UInt64,
    `response.headers.vary` String,
    `response.headers.last_modified` DateTime64(3),
    `response.headers.location` String,
    `response.headers.x_error` String,
    `response.headers.x_surrogate_key` String,
    `response.headers.edge_cache_tag` String,
    `response.headers.edge_control` String
)
AS SELECT
    toDateTime64(timestamp / 1000, 3) AS timestamp,
    'fastly' AS source,
    json.cdn.cache_status AS `cdn.cache_status`,
    json.cdn.cache_ttl AS `cdn.cache_ttl`,
    json.cdn.datacenter AS `cdn.datacenter`,
    json.cdn.is_edge AS `cdn.is_edge`,
    json.cdn.originating_ip AS `cdn.originating_ip`,
    json.cdn.region_code AS `cdn.region_code`,
    json.cdn.time_elapsed_msec AS `cdn.time_elapsed_msec`,
    json.cdn.url AS `cdn.url`,
    json.cdn.version AS `cdn.version`,
    json.client.city_name AS `client.city_name`,
    json.client.country_name AS `client.country_name`,
    json.client.ip AS `client.ip`,
    json.client.name AS `client.name`,
    toUInt32(json.client.number) AS `client.asn`,
    -- NEW: Fixed tech stack value
    'Fastly / Image Optimizer' AS `helix.backend_type`,
    json.helix.contentbus_id AS `helix.contentbus_prefix`,
    'media' AS `helix.request_type`,
    json.request.backend AS `request.backend`,
    0 AS `request.body_size`,
    json.request.host AS `request.host`,
    json.request.method AS `request.method`,
    json.request.protocol AS `request.protocol`,
    json.request.url AS `request.url`,
    json.request.qs AS `request.qs`,
    false AS `request.is_mixed_case`,
    toUInt8(json.request.restarts) AS `request.restarts`,
    json.request.headers.accept_encoding AS `request.headers.accept_encoding`,
    '' AS `request.headers.accept_language`,
    json.request.headers.cache_control AS `request.headers.cache_control`,
    json.request.headers.cdn_loop AS `request.headers.cdn_loop`,
    '' AS `request.headers.referer`,
    '' AS `request.headers.user_agent`,
    '' AS `request.headers.via`,
    json.request.headers.x_forwarded_for AS `request.headers.x_forwarded_for`,
    json.request.headers.x_forwarded_host AS `request.headers.x_forwarded_host`,
    '' AS `request.headers.x_byo_cdn_type`,
    '' AS `request.headers.x_push_invalidation`,
    toUInt16OrZero(json.response.status) AS `response.status`,
    toUInt64(json.response.body_size) AS `response.body_size`,
    json.response.headers.cache_control AS `response.headers.cache_control`,
    json.response.headers.content_type AS `response.headers.content_type`,
    json.response.headers.content_encoding AS `response.headers.content_encoding`,
    toUInt64OrZero(json.response.headers.content_length) AS `response.headers.content_length`,
    '' AS `response.headers.vary`,
    parseDateTime64BestEffortOrZero(json.response.headers.last_modified, 3) AS `response.headers.last_modified`,
    json.response.headers.location AS `response.headers.location`,
    json.response.headers.x_error AS `response.headers.x_error`,
    json.response.headers.surrogate_key AS `response.headers.x_surrogate_key`,
    '' AS `response.headers.edge_cache_tag`,
    json.response.headers.surrogate_control AS `response.headers.edge_control`
FROM helix_logs_production.fastly_logs_incoming_atG7Eq66bH88LhbNq7Fqq2;
-- Tech Stack Migration: fastly_ingestion_admin_v2
-- Changes helix.backend_type from '' to 'Fastly / Admin'

DROP TABLE IF EXISTS helix_logs_production.fastly_ingestion_admin_v2;

CREATE MATERIALIZED VIEW helix_logs_production.fastly_ingestion_admin_v2 TO helix_logs_production.cdn_requests_v2
(
    `timestamp` DateTime64(3),
    `source` String,
    `cdn.cache_status` String,
    `cdn.cache_ttl` UInt8,
    `cdn.datacenter` String,
    `cdn.is_edge` Bool,
    `cdn.originating_ip` String,
    `cdn.region_code` String,
    `cdn.time_elapsed_msec` Float64,
    `cdn.url` String,
    `cdn.version` String,
    `client.city_name` String,
    `client.country_name` String,
    `client.ip` String,
    `client.name` String,
    `client.asn` UInt32,
    `helix.backend_type` String,
    `helix.contentbus_prefix` String,
    `helix.request_type` String,
    `request.backend` String,
    `request.body_size` UInt64,
    `request.host` String,
    `request.method` String,
    `request.protocol` String,
    `request.url` String,
    `request.qs` String,
    `request.is_mixed_case` Bool,
    `request.restarts` UInt8,
    `request.headers.accept_encoding` String,
    `request.headers.accept_language` String,
    `request.headers.cache_control` String,
    `request.headers.cdn_loop` String,
    `request.headers.referer` String,
    `request.headers.user_agent` String,
    `request.headers.via` String,
    `request.headers.x_forwarded_for` String,
    `request.headers.x_forwarded_host` String,
    `request.headers.x_byo_cdn_type` String,
    `request.headers.x_push_invalidation` String,
    `response.status` UInt16,
    `response.body_size` UInt64,
    `response.headers.cache_control` String,
    `response.headers.content_type` String,
    `response.headers.content_encoding` String,
    `response.headers.content_length` UInt64,
    `response.headers.vary` String,
    `response.headers.last_modified` DateTime64(3),
    `response.headers.location` String,
    `response.headers.x_error` String,
    `response.headers.x_surrogate_key` String,
    `response.headers.edge_cache_tag` String,
    `response.headers.edge_control` String
)
AS SELECT
    toDateTime64(timestamp / 1000, 3) AS timestamp,
    'fastly' AS source,
    '' AS `cdn.cache_status`,
    0 AS `cdn.cache_ttl`,
    json.cdn.datacenter AS `cdn.datacenter`,
    false AS `cdn.is_edge`,
    json.cdn.originating_ip AS `cdn.originating_ip`,
    json.cdn.region_code AS `cdn.region_code`,
    json.cdn.time_elapsed_msec AS `cdn.time_elapsed_msec`,
    json.cdn.url AS `cdn.url`,
    json.cdn.version AS `cdn.version`,
    json.client.city_name AS `client.city_name`,
    json.client.country_name AS `client.country_name`,
    json.client.ip AS `client.ip`,
    json.client.name AS `client.name`,
    toUInt32(json.client.number) AS `client.asn`,
    -- NEW: Fixed tech stack value
    'Fastly / Admin' AS `helix.backend_type`,
    concat(json.helix.ref, '--', json.helix.repo, '--', json.helix.owner) AS `helix.contentbus_prefix`,
    json.helix.route AS `helix.request_type`,
    '' AS `request.backend`,
    toUInt64(json.request.body_size) AS `request.body_size`,
    json.request.host AS `request.host`,
    json.request.method AS `request.method`,
    json.request.protocol AS `request.protocol`,
    json.request.url AS `request.url`,
    '' AS `request.qs`,
    false AS `request.is_mixed_case`,
    0 AS `request.restarts`,
    json.request.headers.accept_encoding AS `request.headers.accept_encoding`,
    json.request.headers.accept_language AS `request.headers.accept_language`,
    json.request.headers.cache_control AS `request.headers.cache_control`,
    '' AS `request.headers.cdn_loop`,
    json.request.headers.referer AS `request.headers.referer`,
    json.request.headers.user_agent AS `request.headers.user_agent`,
    json.request.headers.via AS `request.headers.via`,
    json.request.headers.x_forwarded_for AS `request.headers.x_forwarded_for`,
    json.request.headers.x_forwarded_host AS `request.headers.x_forwarded_host`,
    '' AS `request.headers.x_byo_cdn_type`,
    '' AS `request.headers.x_push_invalidation`,
    toUInt16OrZero(json.response.status) AS `response.status`,
    toUInt64(json.response.body_size) AS `response.body_size`,
    '' AS `response.headers.cache_control`,
    json.response.headers.content_type AS `response.headers.content_type`,
    json.response.headers.content_encoding AS `response.headers.content_encoding`,
    toUInt64(json.response.body_size) AS `response.headers.content_length`,
    '' AS `response.headers.vary`,
    parseDateTime64BestEffortOrZero(json.response.headers.last_modified, 3) AS `response.headers.last_modified`,
    json.response.headers.location AS `response.headers.location`,
    json.response.headers.x_error AS `response.headers.x_error`,
    '' AS `response.headers.x_surrogate_key`,
    '' AS `response.headers.edge_cache_tag`,
    '' AS `response.headers.edge_control`
FROM helix_logs_production.fastly_logs_incoming_6a6O21m8WoIIVg5cliw7BW;
-- Tech Stack Migration: fastly_ingestion_api_v2
-- Changes helix.backend_type from '' to 'Fastly / API'

DROP TABLE IF EXISTS helix_logs_production.fastly_ingestion_api_v2;

CREATE MATERIALIZED VIEW helix_logs_production.fastly_ingestion_api_v2 TO helix_logs_production.cdn_requests_v2
(
    `timestamp` DateTime64(3),
    `source` String,
    `cdn.cache_status` String,
    `cdn.cache_ttl` UInt8,
    `cdn.datacenter` String,
    `cdn.is_edge` Bool,
    `cdn.originating_ip` String,
    `cdn.region_code` String,
    `cdn.time_elapsed_msec` Float64,
    `cdn.url` String,
    `cdn.version` String,
    `client.city_name` String,
    `client.country_name` String,
    `client.ip` String,
    `client.name` String,
    `client.asn` UInt32,
    `helix.backend_type` String,
    `helix.contentbus_prefix` String,
    `helix.request_type` String,
    `request.backend` String,
    `request.body_size` UInt64,
    `request.host` String,
    `request.method` String,
    `request.protocol` String,
    `request.url` String,
    `request.qs` String,
    `request.is_mixed_case` Bool,
    `request.restarts` UInt8,
    `request.headers.accept_encoding` String,
    `request.headers.accept_language` String,
    `request.headers.cache_control` String,
    `request.headers.cdn_loop` String,
    `request.headers.referer` String,
    `request.headers.user_agent` String,
    `request.headers.via` String,
    `request.headers.x_forwarded_for` String,
    `request.headers.x_forwarded_host` String,
    `request.headers.x_byo_cdn_type` String,
    `request.headers.x_push_invalidation` String,
    `response.status` UInt16,
    `response.body_size` UInt64,
    `response.headers.cache_control` String,
    `response.headers.content_type` String,
    `response.headers.content_encoding` String,
    `response.headers.content_length` UInt64,
    `response.headers.vary` String,
    `response.headers.last_modified` DateTime64(3),
    `response.headers.location` String,
    `response.headers.x_error` String,
    `response.headers.x_surrogate_key` String,
    `response.headers.edge_cache_tag` String,
    `response.headers.edge_control` String
)
AS SELECT
    toDateTime64(timestamp / 1000, 3) AS timestamp,
    'fastly' AS source,
    '' AS `cdn.cache_status`,
    0 AS `cdn.cache_ttl`,
    json.cdn.datacenter AS `cdn.datacenter`,
    false AS `cdn.is_edge`,
    json.cdn.originating_ip AS `cdn.originating_ip`,
    json.cdn.region_code AS `cdn.region_code`,
    json.cdn.time_elapsed_msec AS `cdn.time_elapsed_msec`,
    json.cdn.url AS `cdn.url`,
    json.cdn.version AS `cdn.version`,
    json.client.city_name AS `client.city_name`,
    json.client.country_name AS `client.country_name`,
    json.client.ip AS `client.ip`,
    json.client.name AS `client.name`,
    toUInt32(json.client.number) AS `client.asn`,
    -- NEW: Fixed tech stack value
    'Fastly / API' AS `helix.backend_type`,
    concat(json.helix.org, '--', json.helix.site) AS `helix.contentbus_prefix`,
    json.helix.topic AS `helix.request_type`,
    '' AS `request.backend`,
    toUInt64(json.request.body_size) AS `request.body_size`,
    json.request.host AS `request.host`,
    json.request.method AS `request.method`,
    json.request.protocol AS `request.protocol`,
    json.request.url AS `request.url`,
    '' AS `request.qs`,
    false AS `request.is_mixed_case`,
    0 AS `request.restarts`,
    json.request.headers.accept_encoding AS `request.headers.accept_encoding`,
    json.request.headers.accept_language AS `request.headers.accept_language`,
    json.request.headers.cache_control AS `request.headers.cache_control`,
    '' AS `request.headers.cdn_loop`,
    json.request.headers.referer AS `request.headers.referer`,
    json.request.headers.user_agent AS `request.headers.user_agent`,
    json.request.headers.via AS `request.headers.via`,
    json.request.headers.x_forwarded_for AS `request.headers.x_forwarded_for`,
    json.request.headers.x_forwarded_host AS `request.headers.x_forwarded_host`,
    '' AS `request.headers.x_byo_cdn_type`,
    '' AS `request.headers.x_push_invalidation`,
    toUInt16OrZero(json.response.status) AS `response.status`,
    toUInt64(json.response.body_size) AS `response.body_size`,
    '' AS `response.headers.cache_control`,
    json.response.headers.content_type AS `response.headers.content_type`,
    json.response.headers.content_encoding AS `response.headers.content_encoding`,
    toUInt64(json.response.body_size) AS `response.headers.content_length`,
    '' AS `response.headers.vary`,
    parseDateTime64BestEffortOrZero(json.response.headers.last_modified, 3) AS `response.headers.last_modified`,
    json.response.headers.location AS `response.headers.location`,
    json.response.headers.x_error AS `response.headers.x_error`,
    '' AS `response.headers.x_surrogate_key`,
    '' AS `response.headers.edge_cache_tag`,
    '' AS `response.headers.edge_control`
FROM helix_logs_production.fastly_logs_incoming_s2dVksBUsvEKaaYF13wIh6;
-- Tech Stack Migration: fastly_ingestion_config_v2
-- Changes helix.backend_type from json.helix.backend_type to 'Fastly / Config'

DROP TABLE IF EXISTS helix_logs_production.fastly_ingestion_config_v2;

CREATE MATERIALIZED VIEW helix_logs_production.fastly_ingestion_config_v2 TO helix_logs_production.cdn_requests_v2
(
    `timestamp` DateTime64(3),
    `source` String,
    `cdn.cache_status` String,
    `cdn.cache_ttl` Float64,
    `cdn.datacenter` String,
    `cdn.is_edge` Bool,
    `cdn.originating_ip` String,
    `cdn.region_code` String,
    `cdn.time_elapsed_msec` Float64,
    `cdn.url` String,
    `cdn.version` String,
    `client.city_name` String,
    `client.country_name` String,
    `client.ip` String,
    `client.name` String,
    `client.asn` UInt32,
    `helix.backend_type` String,
    `helix.contentbus_prefix` String,
    `helix.request_type` String,
    `request.backend` String,
    `request.body_size` UInt64,
    `request.host` String,
    `request.method` String,
    `request.protocol` String,
    `request.url` String,
    `request.qs` String,
    `request.is_mixed_case` Bool,
    `request.restarts` UInt8,
    `request.headers.accept_encoding` String,
    `request.headers.accept_language` String,
    `request.headers.cache_control` String,
    `request.headers.cdn_loop` String,
    `request.headers.referer` String,
    `request.headers.user_agent` String,
    `request.headers.via` String,
    `request.headers.x_forwarded_for` String,
    `request.headers.x_forwarded_host` String,
    `request.headers.x_byo_cdn_type` String,
    `request.headers.x_push_invalidation` String,
    `response.status` UInt16,
    `response.body_size` UInt64,
    `response.headers.cache_control` String,
    `response.headers.content_type` String,
    `response.headers.content_encoding` String,
    `response.headers.content_length` UInt64,
    `response.headers.vary` String,
    `response.headers.last_modified` DateTime64(3),
    `response.headers.location` String,
    `response.headers.x_error` String,
    `response.headers.x_surrogate_key` String,
    `response.headers.edge_cache_tag` String,
    `response.headers.edge_control` String
)
AS SELECT
    toDateTime64(timestamp / 1000, 3) AS timestamp,
    'fastly' AS source,
    json.cdn.cache_status AS `cdn.cache_status`,
    json.cdn.cache_ttl AS `cdn.cache_ttl`,
    json.cdn.datacenter AS `cdn.datacenter`,
    json.cdn.is_edge AS `cdn.is_edge`,
    json.cdn.originating_ip AS `cdn.originating_ip`,
    json.cdn.region_code AS `cdn.region_code`,
    json.cdn.time_elapsed_msec AS `cdn.time_elapsed_msec`,
    json.cdn.url AS `cdn.url`,
    json.cdn.version AS `cdn.version`,
    json.client.city_name AS `client.city_name`,
    json.client.country_name AS `client.country_name`,
    json.client.ip AS `client.ip`,
    json.client.name AS `client.name`,
    toUInt32(json.client.number) AS `client.asn`,
    -- NEW: Fixed tech stack value
    'Fastly / Config' AS `helix.backend_type`,
    json.helix.rso AS `helix.contentbus_prefix`,
    json.helix.scope AS `helix.request_type`,
    json.request.backend AS `request.backend`,
    toUInt64(json.request.body_size) AS `request.body_size`,
    json.request.host AS `request.host`,
    json.request.method AS `request.method`,
    json.request.protocol AS `request.protocol`,
    json.request.url AS `request.url`,
    json.request.qs AS `request.qs`,
    false AS `request.is_mixed_case`,
    toUInt8(json.request.restarts) AS `request.restarts`,
    json.request.headers.accept_encoding AS `request.headers.accept_encoding`,
    json.request.headers.accept_language AS `request.headers.accept_language`,
    json.request.headers.cache_control AS `request.headers.cache_control`,
    json.request.headers.cdn_loop AS `request.headers.cdn_loop`,
    json.request.headers.referer AS `request.headers.referer`,
    json.request.headers.user_agent AS `request.headers.user_agent`,
    json.request.headers.via AS `request.headers.via`,
    json.request.headers.x_forwarded_for AS `request.headers.x_forwarded_for`,
    json.request.headers.x_forwarded_host AS `request.headers.x_forwarded_host`,
    json.request.headers.x_byo_cdn_type AS `request.headers.x_byo_cdn_type`,
    json.request.headers.x_push_invalidation AS `request.headers.x_push_invalidation`,
    toUInt16OrZero(json.response.status) AS `response.status`,
    toUInt64(json.response.body_size) AS `response.body_size`,
    json.response.headers.cache_control AS `response.headers.cache_control`,
    json.response.headers.content_type AS `response.headers.content_type`,
    json.response.headers.content_encoding AS `response.headers.content_encoding`,
    toUInt64(json.response.body_size) AS `response.headers.content_length`,
    json.response.headers.vary AS `response.headers.vary`,
    parseDateTime64BestEffortOrZero(json.response.headers.last_modified, 3) AS `response.headers.last_modified`,
    json.response.headers.location AS `response.headers.location`,
    json.response.headers.x_error AS `response.headers.x_error`,
    json.response.headers.surrogate_key AS `response.headers.x_surrogate_key`,
    '' AS `response.headers.edge_cache_tag`,
    json.response.headers.surrogate_control AS `response.headers.edge_control`
FROM helix_logs_production.fastly_logs_incoming_SIDuP3HxleUgBDR3Gi8T24;
-- Tech Stack Migration: fastly_ingestion_pipeline_v2
-- Changes helix.backend_type from json.helix.backend_type to 'Fastly / Pipeline'

DROP TABLE IF EXISTS helix_logs_production.fastly_ingestion_pipeline_v2;

CREATE MATERIALIZED VIEW helix_logs_production.fastly_ingestion_pipeline_v2 TO helix_logs_production.cdn_requests_v2
(
    `timestamp` DateTime64(3),
    `source` String,
    `cdn.cache_status` String,
    `cdn.cache_ttl` UInt8,
    `cdn.datacenter` String,
    `cdn.is_edge` Bool,
    `cdn.originating_ip` String,
    `cdn.region_code` String,
    `cdn.time_elapsed_msec` Float64,
    `cdn.url` String,
    `cdn.version` String,
    `client.city_name` String,
    `client.country_name` String,
    `client.ip` String,
    `client.name` String,
    `client.asn` UInt8,
    `helix.backend_type` String,
    `helix.contentbus_prefix` String,
    `helix.request_type` String,
    `request.backend` String,
    `request.body_size` UInt8,
    `request.host` String,
    `request.method` String,
    `request.protocol` String,
    `request.url` String,
    `request.qs` String,
    `request.is_mixed_case` Bool,
    `request.restarts` UInt8,
    `request.headers.accept_encoding` String,
    `request.headers.accept_language` String,
    `request.headers.cache_control` String,
    `request.headers.cdn_loop` String,
    `request.headers.referer` String,
    `request.headers.user_agent` String,
    `request.headers.via` String,
    `request.headers.x_forwarded_for` String,
    `request.headers.x_forwarded_host` String,
    `request.headers.x_byo_cdn_type` String,
    `request.headers.x_push_invalidation` String,
    `response.status` UInt16,
    `response.body_size` UInt64,
    `response.headers.cache_control` String,
    `response.headers.content_type` String,
    `response.headers.content_encoding` String,
    `response.headers.content_length` UInt64,
    `response.headers.vary` String,
    `response.headers.last_modified` DateTime64(3),
    `response.headers.location` String,
    `response.headers.x_error` String,
    `response.headers.x_surrogate_key` String,
    `response.headers.edge_cache_tag` String,
    `response.headers.edge_control` String
)
AS SELECT
    toDateTime64(timestamp / 1000, 3) AS timestamp,
    'fastly' AS source,
    '' AS `cdn.cache_status`,
    0 AS `cdn.cache_ttl`,
    json.cdn.datacenter AS `cdn.datacenter`,
    false AS `cdn.is_edge`,
    json.cdn.originating_ip AS `cdn.originating_ip`,
    json.cdn.region_code AS `cdn.region_code`,
    json.cdn.time_elapsed_msec AS `cdn.time_elapsed_msec`,
    json.cdn.url AS `cdn.url`,
    json.cdn.version AS `cdn.version`,
    '' AS `client.city_name`,
    '' AS `client.country_name`,
    '' AS `client.ip`,
    '' AS `client.name`,
    0 AS `client.asn`,
    -- NEW: Fixed tech stack value
    'Fastly / Pipeline' AS `helix.backend_type`,
    json.helix.contentbus_prefix AS `helix.contentbus_prefix`,
    json.helix.request_type AS `helix.request_type`,
    '' AS `request.backend`,
    0 AS `request.body_size`,
    json.request.host AS `request.host`,
    json.request.method AS `request.method`,
    json.request.protocol AS `request.protocol`,
    json.request.url AS `request.url`,
    json.request.qs AS `request.qs`,
    false AS `request.is_mixed_case`,
    toUInt8(json.request.restarts) AS `request.restarts`,
    json.request.headers.accept_encoding AS `request.headers.accept_encoding`,
    '' AS `request.headers.accept_language`,
    '' AS `request.headers.cache_control`,
    '' AS `request.headers.cdn_loop`,
    '' AS `request.headers.referer`,
    '' AS `request.headers.user_agent`,
    '' AS `request.headers.via`,
    '' AS `request.headers.x_forwarded_for`,
    json.request.headers.x_forwarded_host AS `request.headers.x_forwarded_host`,
    '' AS `request.headers.x_byo_cdn_type`,
    '' AS `request.headers.x_push_invalidation`,
    toUInt16OrZero(json.response.status) AS `response.status`,
    toUInt64(json.response.body_size) AS `response.body_size`,
    json.response.headers.cache_control AS `response.headers.cache_control`,
    json.response.headers.content_type AS `response.headers.content_type`,
    json.response.headers.content_encoding AS `response.headers.content_encoding`,
    toUInt64(json.response.body_size) AS `response.headers.content_length`,
    json.response.headers.vary AS `response.headers.vary`,
    parseDateTime64BestEffortOrZero(json.response.headers.last_modified, 3) AS `response.headers.last_modified`,
    json.response.headers.location AS `response.headers.location`,
    json.response.headers.x_error AS `response.headers.x_error`,
    json.response.headers.surrogate_key AS `response.headers.x_surrogate_key`,
    '' AS `response.headers.edge_cache_tag`,
    json.response.headers.surrogate_control AS `response.headers.edge_control`
FROM helix_logs_production.fastly_logs_incoming_cHpjIl1WNRu9SFyL1eBSj3;
-- Tech Stack Migration: fastly_ingestion_static_v2
-- Changes helix.backend_type from json.helix.backend_type to 'Fastly / Static'

DROP TABLE IF EXISTS helix_logs_production.fastly_ingestion_static_v2;

CREATE MATERIALIZED VIEW helix_logs_production.fastly_ingestion_static_v2 TO helix_logs_production.cdn_requests_v2
(
    `timestamp` DateTime64(3),
    `source` String,
    `cdn.cache_status` String,
    `cdn.cache_ttl` UInt8,
    `cdn.datacenter` String,
    `cdn.is_edge` Bool,
    `cdn.originating_ip` String,
    `cdn.region_code` String,
    `cdn.time_elapsed_msec` Float64,
    `cdn.url` String,
    `cdn.version` String,
    `client.city_name` String,
    `client.country_name` String,
    `client.ip` String,
    `client.name` String,
    `client.asn` UInt32,
    `helix.backend_type` String,
    `helix.contentbus_prefix` String,
    `helix.request_type` String,
    `request.backend` String,
    `request.body_size` UInt8,
    `request.host` String,
    `request.method` String,
    `request.protocol` String,
    `request.url` String,
    `request.qs` String,
    `request.is_mixed_case` Bool,
    `request.restarts` UInt8,
    `request.headers.accept_encoding` String,
    `request.headers.accept_language` String,
    `request.headers.cache_control` String,
    `request.headers.cdn_loop` String,
    `request.headers.referer` String,
    `request.headers.user_agent` String,
    `request.headers.via` String,
    `request.headers.x_forwarded_for` String,
    `request.headers.x_forwarded_host` String,
    `request.headers.x_byo_cdn_type` String,
    `request.headers.x_push_invalidation` String,
    `response.status` UInt16,
    `response.body_size` UInt64,
    `response.headers.cache_control` String,
    `response.headers.content_type` String,
    `response.headers.content_encoding` String,
    `response.headers.content_length` UInt64,
    `response.headers.vary` String,
    `response.headers.last_modified` DateTime64(3),
    `response.headers.location` String,
    `response.headers.x_error` String,
    `response.headers.x_surrogate_key` String,
    `response.headers.edge_cache_tag` String,
    `response.headers.edge_control` String
)
AS SELECT
    toDateTime64(timestamp / 1000, 3) AS timestamp,
    'fastly' AS source,
    '' AS `cdn.cache_status`,
    0 AS `cdn.cache_ttl`,
    json.cdn.datacenter AS `cdn.datacenter`,
    false AS `cdn.is_edge`,
    '' AS `cdn.originating_ip`,
    json.cdn.region_code AS `cdn.region_code`,
    json.cdn.time_elapsed_msec AS `cdn.time_elapsed_msec`,
    '' AS `cdn.url`,
    json.cdn.version AS `cdn.version`,
    json.client.city_name AS `client.city_name`,
    json.client.country_name AS `client.country_name`,
    json.client.ip AS `client.ip`,
    json.client.name AS `client.name`,
    toUInt32(json.client.number) AS `client.asn`,
    -- NEW: Fixed tech stack value
    'Fastly / Static' AS `helix.backend_type`,
    json.helix.contentbus_prefix AS `helix.contentbus_prefix`,
    json.helix.request_type AS `helix.request_type`,
    json.request.backend AS `request.backend`,
    0 AS `request.body_size`,
    json.request.host AS `request.host`,
    json.request.method AS `request.method`,
    json.request.protocol AS `request.protocol`,
    json.request.url AS `request.url`,
    '' AS `request.qs`,
    false AS `request.is_mixed_case`,
    toUInt8(json.request.restarts) AS `request.restarts`,
    json.request.headers.accept_encoding AS `request.headers.accept_encoding`,
    '' AS `request.headers.accept_language`,
    '' AS `request.headers.cache_control`,
    json.request.headers.cdn_loop AS `request.headers.cdn_loop`,
    '' AS `request.headers.referer`,
    '' AS `request.headers.user_agent`,
    json.request.headers.via AS `request.headers.via`,
    '' AS `request.headers.x_forwarded_for`,
    json.request.headers.x_forwarded_host AS `request.headers.x_forwarded_host`,
    '' AS `request.headers.x_byo_cdn_type`,
    '' AS `request.headers.x_push_invalidation`,
    toUInt16OrZero(json.response.status) AS `response.status`,
    toUInt64(json.response.body_size) AS `response.body_size`,
    '' AS `response.headers.cache_control`,
    json.response.headers.content_type AS `response.headers.content_type`,
    json.response.headers.content_encoding AS `response.headers.content_encoding`,
    toUInt64(json.response.body_size) AS `response.headers.content_length`,
    json.response.headers.vary AS `response.headers.vary`,
    parseDateTime64BestEffortOrZero(json.response.headers.last_modified, 3) AS `response.headers.last_modified`,
    json.response.headers.location AS `response.headers.location`,
    json.response.headers.x_error AS `response.headers.x_error`,
    json.response.headers.surrogate_key AS `response.headers.x_surrogate_key`,
    '' AS `response.headers.edge_cache_tag`,
    '' AS `response.headers.edge_control`
FROM helix_logs_production.fastly_logs_incoming_ItVEMJu5q2pJE3ejseo0W6;
-- Tech Stack Migration: fastly_ingestion_www_v2
-- Changes helix.backend_type from '' to 'Fastly / WWW'

DROP TABLE IF EXISTS helix_logs_production.fastly_ingestion_www_v2;

CREATE MATERIALIZED VIEW helix_logs_production.fastly_ingestion_www_v2 TO helix_logs_production.cdn_requests_v2
(
    `timestamp` DateTime64(3),
    `source` String,
    `cdn.cache_status` String,
    `cdn.cache_ttl` Float64,
    `cdn.datacenter` String,
    `cdn.is_edge` Bool,
    `cdn.originating_ip` String,
    `cdn.region_code` String,
    `cdn.time_elapsed_msec` Float64,
    `cdn.url` String,
    `cdn.version` String,
    `client.city_name` String,
    `client.country_name` String,
    `client.ip` String,
    `client.name` String,
    `client.asn` UInt32,
    `helix.backend_type` String,
    `helix.contentbus_prefix` String,
    `helix.request_type` String,
    `request.backend` String,
    `request.body_size` UInt64,
    `request.host` String,
    `request.method` String,
    `request.protocol` String,
    `request.url` String,
    `request.qs` String,
    `request.is_mixed_case` Bool,
    `request.restarts` UInt8,
    `request.headers.accept_encoding` String,
    `request.headers.accept_language` String,
    `request.headers.cache_control` String,
    `request.headers.cdn_loop` String,
    `request.headers.referer` String,
    `request.headers.user_agent` String,
    `request.headers.via` String,
    `request.headers.x_forwarded_for` String,
    `request.headers.x_forwarded_host` String,
    `request.headers.x_byo_cdn_type` String,
    `request.headers.x_push_invalidation` String,
    `response.status` UInt16,
    `response.body_size` UInt64,
    `response.headers.cache_control` String,
    `response.headers.content_type` String,
    `response.headers.content_encoding` String,
    `response.headers.content_length` UInt64,
    `response.headers.vary` String,
    `response.headers.last_modified` DateTime64(3),
    `response.headers.location` String,
    `response.headers.x_error` String,
    `response.headers.x_surrogate_key` String,
    `response.headers.edge_cache_tag` String,
    `response.headers.edge_control` String
)
AS SELECT
    toDateTime64(timestamp / 1000, 3) AS timestamp,
    'fastly' AS source,
    json.cdn.cache_status AS `cdn.cache_status`,
    json.cdn.cache_ttl AS `cdn.cache_ttl`,
    json.cdn.datacenter AS `cdn.datacenter`,
    json.cdn.is_edge AS `cdn.is_edge`,
    json.cdn.originating_ip AS `cdn.originating_ip`,
    json.cdn.region_code AS `cdn.region_code`,
    json.cdn.time_elapsed_msec AS `cdn.time_elapsed_msec`,
    json.cdn.url AS `cdn.url`,
    json.cdn.version AS `cdn.version`,
    json.client.city_name AS `client.city_name`,
    json.client.country_name AS `client.country_name`,
    json.client.ip AS `client.ip`,
    json.client.name AS `client.name`,
    toUInt32(json.client.number) AS `client.asn`,
    -- NEW: Fixed tech stack value
    'Fastly / WWW' AS `helix.backend_type`,
    '' AS `helix.contentbus_prefix`,
    '' AS `helix.request_type`,
    json.request.backend AS `request.backend`,
    toUInt64(json.request.body_size) AS `request.body_size`,
    json.request.host AS `request.host`,
    json.request.method AS `request.method`,
    json.request.protocol AS `request.protocol`,
    json.request.url AS `request.url`,
    json.request.qs AS `request.qs`,
    false AS `request.is_mixed_case`,
    toUInt8(json.request.restarts) AS `request.restarts`,
    json.request.headers.accept_encoding AS `request.headers.accept_encoding`,
    json.request.headers.accept_language AS `request.headers.accept_language`,
    json.request.headers.cache_control AS `request.headers.cache_control`,
    '' AS `request.headers.cdn_loop`,
    json.request.headers.referer AS `request.headers.referer`,
    json.request.headers.user_agent AS `request.headers.user_agent`,
    json.request.headers.via AS `request.headers.via`,
    json.request.headers.x_forwarded_for AS `request.headers.x_forwarded_for`,
    json.request.headers.x_forwarded_host AS `request.headers.x_forwarded_host`,
    '' AS `request.headers.x_byo_cdn_type`,
    '' AS `request.headers.x_push_invalidation`,
    toUInt16OrZero(json.response.status) AS `response.status`,
    toUInt64(json.response.body_size) AS `response.body_size`,
    json.response.headers.cache_control AS `response.headers.cache_control`,
    json.response.headers.content_type AS `response.headers.content_type`,
    json.response.headers.content_encoding AS `response.headers.content_encoding`,
    toUInt64(json.response.body_size) AS `response.headers.content_length`,
    json.response.headers.vary AS `response.headers.vary`,
    parseDateTime64BestEffortOrZero(json.response.headers.last_modified, 3) AS `response.headers.last_modified`,
    json.response.headers.location AS `response.headers.location`,
    json.response.headers.x_error AS `response.headers.x_error`,
    json.response.headers.surrogate_key AS `response.headers.x_surrogate_key`,
    '' AS `response.headers.edge_cache_tag`,
    '' AS `response.headers.edge_control`
FROM helix_logs_production.fastly_logs_incoming_00QRLuuAsVNvsKgNWYVCbb;
-- Tech Stack Migration: fastly_ingestion_form_v2
-- Changes helix.backend_type from '' to 'Fastly / Forms'

DROP TABLE IF EXISTS helix_logs_production.fastly_ingestion_form_v2;

CREATE MATERIALIZED VIEW helix_logs_production.fastly_ingestion_form_v2 TO helix_logs_production.cdn_requests_v2
(
    `timestamp` DateTime64(3),
    `source` String,
    `cdn.cache_status` String,
    `cdn.cache_ttl` UInt8,
    `cdn.datacenter` String,
    `cdn.is_edge` Bool,
    `cdn.originating_ip` String,
    `cdn.region_code` String,
    `cdn.time_elapsed_msec` Float64,
    `cdn.url` String,
    `cdn.version` String,
    `client.city_name` String,
    `client.country_name` String,
    `client.ip` String,
    `client.name` String,
    `client.asn` UInt32,
    `helix.backend_type` String,
    `helix.contentbus_prefix` String,
    `helix.request_type` String,
    `request.backend` String,
    `request.body_size` UInt64,
    `request.host` String,
    `request.method` String,
    `request.protocol` String,
    `request.url` String,
    `request.qs` String,
    `request.is_mixed_case` Bool,
    `request.restarts` UInt8,
    `request.headers.accept_encoding` String,
    `request.headers.accept_language` String,
    `request.headers.cache_control` String,
    `request.headers.cdn_loop` String,
    `request.headers.referer` String,
    `request.headers.user_agent` String,
    `request.headers.via` String,
    `request.headers.x_forwarded_for` String,
    `request.headers.x_forwarded_host` String,
    `request.headers.x_byo_cdn_type` String,
    `request.headers.x_push_invalidation` String,
    `response.status` UInt16,
    `response.body_size` UInt64,
    `response.headers.cache_control` String,
    `response.headers.content_type` String,
    `response.headers.content_encoding` String,
    `response.headers.content_length` UInt64,
    `response.headers.vary` String,
    `response.headers.last_modified` DateTime64(3),
    `response.headers.location` String,
    `response.headers.x_error` String,
    `response.headers.x_surrogate_key` String,
    `response.headers.edge_cache_tag` String,
    `response.headers.edge_control` String
)
AS SELECT
    toDateTime64(timestamp / 1000, 3) AS timestamp,
    'fastly' AS source,
    '' AS `cdn.cache_status`,
    0 AS `cdn.cache_ttl`,
    text.cdn.datacenter AS `cdn.datacenter`,
    false AS `cdn.is_edge`,
    text.cdn.originating_ip AS `cdn.originating_ip`,
    text.cdn.region_code AS `cdn.region_code`,
    toFloat64(text.cdn.time.elapsed) / 1000. AS `cdn.time_elapsed_msec`,
    text.cdn.url AS `cdn.url`,
    text.cdn.version AS `cdn.version`,
    text.cdn.client.city_name AS `client.city_name`,
    text.cdn.client.country_name AS `client.country_name`,
    text.cdn.client.ip AS `client.ip`,
    text.cdn.client.name AS `client.name`,
    toUInt32(text.cdn.client.number) AS `client.asn`,
    -- NEW: Fixed tech stack value
    'Fastly / Forms' AS `helix.backend_type`,
    '' AS `helix.contentbus_prefix`,
    'form' AS `helix.request_type`,
    text.cdn.request.backend AS `request.backend`,
    toUInt64(text.cdn.request.body_size) AS `request.body_size`,
    text.cdn.request.host AS `request.host`,
    text.cdn.request.method AS `request.method`,
    text.cdn.request.protocol AS `request.protocol`,
    text.cdn.request.url AS `request.url`,
    '' AS `request.qs`,
    false AS `request.is_mixed_case`,
    0 AS `request.restarts`,
    '' AS `request.headers.accept_encoding`,
    '' AS `request.headers.accept_language`,
    '' AS `request.headers.cache_control`,
    '' AS `request.headers.cdn_loop`,
    text.cdn.request.headers.referer AS `request.headers.referer`,
    text.cdn.request.headers.user_agent AS `request.headers.user_agent`,
    '' AS `request.headers.via`,
    text.cdn.request.headers.x_forwarded_for AS `request.headers.x_forwarded_for`,
    text.cdn.request.headers.x_forwarded_host AS `request.headers.x_forwarded_host`,
    '' AS `request.headers.x_byo_cdn_type`,
    '' AS `request.headers.x_push_invalidation`,
    toUInt16OrZero(text.cdn.response.status) AS `response.status`,
    toUInt64(text.cdn.response.body_size) AS `response.body_size`,
    '' AS `response.headers.cache_control`,
    '' AS `response.headers.content_type`,
    '' AS `response.headers.content_encoding`,
    toUInt64(text.cdn.response.body_size) AS `response.headers.content_length`,
    '' AS `response.headers.vary`,
    toDateTime64(0, 3) AS `response.headers.last_modified`,
    '' AS `response.headers.location`,
    text.cdn.response.headers.x_error AS `response.headers.x_error`,
    '' AS `response.headers.x_surrogate_key`,
    '' AS `response.headers.edge_cache_tag`,
    '' AS `response.headers.edge_control`
FROM helix_logs_production.fastly_logs_incoming_UDBDj4zfyNdZEpZApUqhL3;
